from marshmallow import schema, ValidationError, fields
from enum import Enum

class State(Enum):
    FCT='fct'
    ABIA='abia'
    ADAMAWA='adamawa'
    AKWA_IBOM='akwa ibom'
    ANAMBRA='anambra'
    BAUCHI='bauchi'
    BAYELSA='bayelsa'
    BENUE='benue'
    BORNO='borno'
    CROSS_RIVER='cross river'
    DELTA='delta'
    EBONYI='ebonyi'
    EDO='edo'
    EKITI='ekiti'
    ENUGU='enugu'
    GOMBE='gombe'
    IMO='imo'
    JIGAWA='jigawa'
    KADUNA='kaduna'
    KANO='kano'
    KATSINA='katsina'
    KEBBI='kebbi'
    KOGI='kogi'
    KWARA='kwara'
    LAGOS='lagos'
    NASARAWA='nasarawa'
    NIGER='niger'
    OGUN='ogun'
    OSUN='osun'
    OYO='oyo'
    PLATEAU='plateau'
    RIVERS='rivers'
    SOKOTO='sokoto'
    TARABA='taraba'
    YOBE='yobe'
    ZAMFARA='zamfara'

class Category(Enum):
    PERCUSSION='percussion'
    IDIOPHONES='idiophones'
    MEMBRANOPHONES='membranes'
    